# Generated by Django 4.2.11 on 2024-12-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='', max_length=50, verbose_name='ФИО')),
                ('birth', models.DateField()),
                ('med_num', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Ребенок',
                'verbose_name_plural': 'Дети',
            },
        ),
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='', max_length=50, verbose_name='ФИО')),
                ('job_title', models.CharField(choices=[('Врач', 'Врач'), ('Медсестра', 'Медсестра'), ('Администратор', 'Администратор')], default='', max_length=25)),
            ],
            options={
                'verbose_name': 'Медицинский работник',
                'verbose_name_plural': 'Медицинские работники',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(default='', max_length=100, verbose_name='контактная информация')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='прививка')),
                ('introduction_schedule', models.DateField()),
                ('contraindications', models.TextField()),
                ('side_effects', models.TextField()),
            ],
            options={
                'verbose_name': 'Вакцина',
                'verbose_name_plural': 'Вакцины',
            },
        ),
        migrations.CreateModel(
            name='MedicalCard',
            fields=[
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Privivki.children')),
                ('medical_story', models.TextField()),
                ('current_health_status', models.TextField()),
            ],
            options={
                'verbose_name': 'Медицинская карточка',
                'verbose_name_plural': 'Медицинская карточка',
            },
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Privivki.children')),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Privivki.vaccination')),
            ],
            options={
                'verbose_name': 'График вакцинации',
                'verbose_name_plural': 'График вакцинаций',
            },
        ),
        migrations.CreateModel(
            name='VaccinationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_date', models.DateField()),
                ('type_vaccination', models.CharField(max_length=25)),
                ('dosage', models.CharField(max_length=50)),
                ('med_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Privivki.medicalstaff')),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Privivki.vaccination')),
            ],
            options={
                'verbose_name': 'Журнал прививок',
                'verbose_name_plural': 'Журнал прививок',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_of_generation', models.DateField(auto_now_add=True)),
                ('med_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Privivki.medicalstaff')),
            ],
            options={
                'verbose_name': 'отчет',
                'verbose_name_plural': 'отчёты',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_of_send', models.DateField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Privivki.parent')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
            },
        ),
        migrations.AddField(
            model_name='children',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Privivki.parent'),
        ),
    ]
