# Generated by Django 4.2.11 on 2024-12-10 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Privivki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationschedule',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Privivki.children', verbose_name='Ребенок'),
        ),
        migrations.AlterField(
            model_name='vaccinationschedule',
            name='scheduled_date',
            field=models.DateField(verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='vaccinationschedule',
            name='vaccination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Privivki.vaccination', verbose_name='Прививка'),
        ),
    ]
